services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/seu-usuario/seu-repositorio
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: laravel_db
      - key: DB_DATABASE
        fromDatabase: laravel_db
      - key: DB_USERNAME
        fromDatabase: laravel_db
      - key: DB_PASSWORD
        fromDatabase: laravel_db
